#!/bin/bash

if [[ $USER != "root" ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

# initialisasi var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;

MYIP=$(ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1)
if [ "$MYIP" = "" ]; then
	MYIP=$(wget -qO- ipv4.icanhazip.com)
fi
MYIP2="s/xxxxxxxxx/$MYIP/g";
MYIP3="s/xxxxxxxxx:443/$MYIP:443/g";
ether=`ifconfig | cut -c 1-8 | sort | uniq -u | grep venet0 | grep -v venet0:`
if [[ $ether = "" ]]; then
        ether=eth0
fi

	source="http://www.borneobesthosting.me/autoscript"

# go to root
cd
# Install lolcat
apt-get install bc -y
apt-get install xfonts-thai* -y
apt-get install figlet
apt-get install ruby -y
apt-get install unzip
wget https://github.com/busyloop/lolcat/archive/master.zip
cd lolcat-master/bin
gem install lolcat
cd
rm -r lolcat-master
rm master.zip

# check registered ip
wget -q -O IP $source/Debian7/IP.txt
if ! grep -w -q $MYIP IP; then
	echo "Maaf, hanya IP yang terdaftar yang bisa menggunakan script ini!" | lolcat
        echo "     
                       
clear
echo ""
echo "   WELCOME TO AUTOSCRIPT SERVICE "| lolcat
echo "  ===================================================================="| lolcat
echo "  # 	                   Contact Me                            #"| lolcat
echo "  #            TELEGRAM  :  https://t.me/orangkuatsabahanterkini     #"| lolcat
echo "  #               GROUP  :   https://                                #"| lolcat
echo "  #             CHANNEL  : @NewPremiumService                        #"| lolcat
echo "  #------------------------------------------------------------------#"| lolcat
echo "  ===================================================================="| lolcat
	
	rm /root/IP
	rm -f /root/IP
	exit
  
fi
# go to root
cd
