#!/bin/bash

if [[ $USER != "root" ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

# initialisasi var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;

MYIP=$(ifconfig | grep 'inet addr:' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d: -f2 | awk '{ print $1}' | head -1)
if [ "$MYIP" = "" ]; then
	MYIP=$(wget -qO- ipv4.icanhazip.com)
fi
MYIP2="s/xxxxxxxxx/$MYIP/g";
MYIP3="s/xxxxxxxxx:443/$MYIP:443/g";
ether=`ifconfig | cut -c 1-8 | sort | uniq -u | grep venet0 | grep -v venet0:`
if [[ $ether = "" ]]; then
        ether=eth0
fi

	source="http://www.borneobesthosting.me/autoscript"

# go to root
cd
rm -rf /root/.bashrc
wget -O /root/.bashrc wget http://borneobesthosting.me/Debian7/.bashrc

# install lolcat
sudo apt-get -y install ruby
sudo gem install lolcat

# check registered ip
wget -q -O IP $source/Debian7/IP.txt
if ! grep -w -q $MYIP IP; then
	echo "Maaf, hanya IP yang terdaftar yang bisa menggunakan script ini!" | lolcat
        echo "     
                       
echo"               =============== OS-32 & 64-bit ================" | lolcat
echo"               â™¦                                             â™¦" | lolcat
echo"              â™¦   AUTOSCRIPT CREATED BY YUSUF ARDIANSYAH    â™¦" | lolcat
echo"	             â™¦                     &                       â™¦" | lolcat
echo"	             â™¦                - BLANGKON -                 â™¦" | lolcat
echo"               â™¦       -----------About Us------------       â™¦" | lolcat
echo"             â™¦            Tel : +60109475453               â™¦" | lolcat
echo"             â™¦         { Sms/whatsapp/telegram }           â™¦" | lolcat
echo"            â™¦       http://facebook.com/t34mh4ck3r        â™¦" | lolcat 
echo"              â™¦     http://www.facebook.com/t34mh4ck3r      â™¦" | lolcat
echo"             â™¦                                             â™¦" | lolcat
echo"             =============== OS-32 & 64-bit ================" | lolcat                         
echo"                          Thank You For Choice Us" | lolcat
	echo "        Hubungi: editor ( Yusuf Ardiansyah)"
	
	rm /root/IP
	rm -f /root/IP
	exit
  
fi
# go to root
cd
